volumes:
  db_data:
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: 'web'
    env_file: .env.web
    ports:
      - "3000:80"
    volumes:
      - .:/var/www/html
    container_name: web_service

  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cwatch_creditwatch
      MYSQL_PASSWORD:
    container_name: database_service

  feature_flag:
    build:
      context: .
      dockerfile: Dockerfile
      target: 'feature_flag'
    env_file: .env.feature-flag
    ports:
      - "3001:80"
    volumes:
      - ./FeatureFlag:/var/www/html
    container_name: feature_flag_service